package ga_MSA;

/**
 * 
 *  >beta globin
	MVHLTPEEKSAVTALWGKVNVDEVGGEALGRLLVVYPWTQRFFESFGDLSTPDAVMGNPKVKAHGKKVLGAFS
	DGLAHLDNLKGTFATLSELHCDKLHVDPENFRLLGNVLVCVLAHHFGKEFTPPVQAAYQKVVAGVANALAHKYH
	>myoglobin
	MGLSDGEWQLVLNVWGKVEADIPGHGQEVLIRLFKGHPETLEKFDKFKHLKSEDEMKASEDLKKHGATVLTAL
	GGILKKKGHHEAEIKPLAQSHATKHKIPVKYLEFISECIIQVLQSKHPGDFGADAQGAMNKALELFRKDMASNYKELGFQG
	>neuroglobin
	MERPEPELIRQSWRAVSRSPLEHGTVLFARLFALEPDLLPLFQYNCRQFSSPEDCLSSPEFLDHIRKVMLVIDA
	AVTNVEDLSSLEEYLASLGRKHRAVGVKLSSFSTVGESLLYMLEKCLGPAFTPATRAAWSQLYGAVVQAMSRGWDGE
	>soybean
	MVAFTEKQDALVSSSFEAFKANIPQYSVVFYTSILEKAPAAKDLFSFLANGVDPTNPKLTGHAEKLFALVRDSA
	GQLKASGTVVADAALGSVHAQKAVTDPQFVVVKEALLKTIKAAVGDKWSDELSRAWEVAYDELAAAIKKA
	>rice
	MALVEDNNAVAVSFSEEQEALVLKSWAILKKDSANIALRFFLKIFEVAPSASQMFSFLRNSDVPLEKNPKLKTHA
	MSVFVMTCEAAAQLRKAGKVTVRDTTLKRLGATHLKYGVGDAHFEVVKFALLDTIKEEVPADMWSPAMKSAWSEAYDHLVAAIKQEMKPAE
 *
 */

public class MSA {
	
	private String[] seq;
	private int[] size;
	public int maxW = 5;
	public int maxL;
	
	public MSA () {
		seq = new String[maxW];
		//seq[0] = "CCCATTAT";
		//seq[1] = "ATAT";
		//seq[2] = "CCTGA";
		seq[0] = "MVHLTPEEKSAVTALWGKVNVDEVGGEALGRLLVVYPWTQRFFESFG" +
				 "DLSTPDAVMGNPKVKAHGKKVLGAFSDGLAHLDNLKGTFATLSELHCDKLHVDPE" +
				 "NFRLLGNVLVCVLAHHFGKEFTPPVQAAYQKVVAGVANALAHKYH";
		seq[1] = "MGLSDGEWQLVLNVWGKVEADIPGHGQEVLIRLFKGHPETLEKFDKFK" +
				 "HLKSEDEMKASEDLKKHGATVLTALGGILKKKGHHEAEIKPLAQSHATKHKIPVK" +
				 "YLEFISECIIQVLQSKHPGDFGADAQGAMNKALELFRKDMASNYKELGFQG";
		seq[2] = "MERPEPELIRQSWRAVSRSPLEHGTVLFARLFALEPDLLPLFQYNCR" +
				 "QFSSPEDCLSSPEFLDHIRKVMLVIDAAVTNVEDLSSLEEYLASLGRKHRAVGVKLS" +
				 "SFSTVGESLLYMLEKCLGPAFTPATRAAWSQLYGAVVQAMSRGWDGE";
		seq[3] = "MVAFTEKQDALVSSSFEAFKANIPQYSVVFYTSILEKAPAAKDLFSFLA" +
				 "NGVDPTNPKLTGHAEKLFALVRDSAGQLKASGTVVADAALGSVHAQKAVTDP" +
				 "QFVVVKEALLKTIKAAVGDKWSDELSRAWEVAYDELAAAIKKA";
		seq[4] = "MALVEDNNAVAVSFSEEQEALVLKSWAILKKDSANIALRFFLKIFEVAPSASQMFSFLR" +
				 "NSDVPLEKNPKLKTHAMSVFVMTCEAAAQLRKAGKVTVRDTTLKRLGATHLKYGVGDA" +
				 "HFEVVKFALLDTIKEEVPADMWSPAMKSAWSEAYDHLVAAIKQEMKPAE";
		
		size = new int[maxW];
		for (int i = 0; i < maxW; i++) {
			size[i] = seq[i].length();
			if (size[i] > maxL)
				maxL = size[i];
		}
		//adding 10 gaps
		maxL += 10;
	}
	
	public int length(int index) {
		return size[index];
	}
	
	public char getChar(int W, int L) {
		return seq[W].charAt(L);
	}

}
